services:
  - type: web
    name: urlshort-api
    env: node
    rootDir: server
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://fiwsza007.github.io
      - key: DB_FILE
        value: /opt/render/project/src/data.sqlite